baseurl = "https://usistem.com"
metaDataFormat = "yaml"
title = "Circle: Build your own system"
keywords= ['build', 'system', 'machine']
theme = "blist"
staticDir = ['static', 'images']
#uglyurls = true
image = "/images/circle-data-chart.png"

DefaultContentLanguage = "zh"
DefaultContentLanguageInSubdir = true

googleAnalytics = 'G-8T78BT60ZH'

[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 2
    languageName = "English"
    staticDir = 'static_en'
    [languages.en.params]
      introTitle = "Quantifiedself"
      introSubtitle = "If it's not recorded, it didn't happen; if it's not quantified, it can't be optimized."
      #introPhoto = "picture.jpg"
      #logo = "blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "The Bay Area"
        url = "the-bay-area"
        weight = 2

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 3

    [[languages.en.menu.main]]
        name = "Privacy"
        url = "page/privacy/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Support"
        url = "page/support/"
        weight = 5

  [languages.zh]
    contentDir = "content/zh" # Chinese
    weight = 1
    languageName = "Chinese"
    title = "集合"
    keywords = ["构建", "个人系统", "机器"]
    description = "量化自我，看见成长"
    staticDir = 'static_zh'
    [languages.zh.params]
      introTitle = "集合量化"
      introSubtitle = "没有记录就没有发生，没有量化便无法优化"
      #introPhoto = "picture.jpg"
      #logo = "blist-logo.png"
    [[languages.zh.menu.main]]
        name = "博客"
        url = "blog"
        weight = 1

    [[languages.zh.menu.main]]
        name = "湾区"
        url = "the-bay-area"
        weight = 2

    [[languages.zh.menu.main]]
        name = "关于"
        url = "page/about/"
        weight = 3

    [[languages.zh.menu.main]]
        name = "隐私"
        url = "page/privacy/"
        weight = 4

    [[languages.zh.menu.main]]
        name = "支持"
        url = "page/support/"
        weight = 5

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  image = "https://usistem.com/images/circle-data-chart.png"

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - 集合量化, Ltd · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  # ascentColor = "bg-blue-100"
  ascentColor = "bg-orange-500"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = true

[params.homepage.social]
  # Global params common for both languages
  #title = "Follow me"

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/hagerhu"
  [[params.homepage.social.icons]]
    website = "telegram"
    url = "https://t.me/hagerhu"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/hagerhu"
  [[params.homepage.social.icons]]
    website = "medium"
    url = "https://medium.com/@hagerhu"
  [[params.homepage.social.icons]]
    website = "dribbble"
    url = "https://dribbble.com/hagerhu"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://youtube.com/@hagerhu"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Referrer-Policy = 'no-referrer'